DROP TABLE posts;
DROP TABLE users;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE posts (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users (id),
	public BOOLEAN NOT NULL DEFAULT TRUE,
	text TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW()
);